version:2.1

jobs:
 test1:
  docker:
   - image: python:3.6
  steps:
   - checkout
   - run: pip install flask pytest
   - run: py.test

test2:
 docker:
  -image:python:3.6
 steps:
  - checkout
  -run: pip install flask pytest
  -run: py.test

slack_notify:
 machine: true
 steps:
  -run: "curl-XPOST-H'Content-type:application/json'--data'{\"text\":\"Hello,jaekkim!\"}'${SLACK_API_URL}"

workflows:
 welcome:
  jobs:
   - test1
   - test2
   -slack_notify:
     requires:
      - test1
      - test2
