# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
jobs:
 hello:
  machine: true
  steps:
   - checkout
   - run: TEXT="cat message.txt"
   - run: echo "Hello, world!"
   - run: cat .circleci/config.yml
   - run: "curl -X POST -H 'Content-type: application/json' --data '{\"text\":\"'${TEXT}'\"}' ${SLACK_API_URL}"
   
workflows:
 welcome:
  jobs:
   - hello 
